### PR TITLE
Fix HTTPS redirect port

### LINKED ISSUE #1: Backoffice fails to load if missing trailing `/`
When loading Backoffice with a missing trailing `/` the initial resource loads due to the [current nginx config](https://github.com/PlaceOS/nginx/blob/4d89b5f88cddba0acdb2827bf565cf523e9469e5/config/nginx.conf#L59) however other required assets do not.

mail

### PR DESCRIPTION
**Pull request by kimburgess**
Adds support operating on externally remapped ports without breaking things when upgrading from http -> https.

A `HTTPS_REDIRECT_PORT` environment variable can be used to explicitly specify this. If unset, default to the port component of `PLACE_DOMAIN` that is used for SSL cert generation.

Resolves #1.

### CODE REVIEW

**Comment by w-le** [comment]
oh but with this change, nginx would always redirect to just a single domain right?
so it wouldn't be possible for the single placeos instance to be access from multiple domains, which is actually a very common use case

**Comment by kimburgess** [comment]
Ah yes. Very good point. One moment...

**Comment by kimburgess** [comment]
Bump @w-le.

**Review by w-le — APPROVED** [review]
nice looks good to me

**Pull request merged**
